FROM pytorch/pytorch:2.9.1-cuda12.8-cudnn9-runtime

RUN apt-get -y update && \
    apt-get install -y --no-install-recommends git && \
    apt-get autoclean && \
    rm -rf /var/lib/apt/lists/*

RUN git clone --depth=1 https://github.com/NeuroADaS-Lab/TimeLesSeg.git /app && \
    cd /app && \
    pip install --upgrade pip && \
    pip install --no-cache-dir .

WORKDIR /app

# owner: 6 - read & write; group: 4 - read; other: 4 - read
COPY --chmod=644 \
     trained_models/resunet_128_128_96_20_09_25/checkpoint_final.pth \
     trained_models/resunet_128_128_96_20_09_25/checkpoint_best.pth \
     trained_models/resunet_128_128_96_20_09_25/dataset_fingerprint.json \
     trained_models/resunet_128_128_96_20_09_25

ENTRYPOINT [ "/usr/bin/bash", "/app/timelesseg_containerized.sh" ]